# -*- coding: utf-8 -*-
"""FLOPs and Inference Time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNNMWYZxbTswBk9I7mUpmW7-hqshiBGE
"""

import time
import numpy as np
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2_as_graph
import logging

# Suppress TF warnings to keep output clean
tf.get_logger().setLevel(logging.ERROR)

print("Loading models...")

# Load baseline model
cnn_model = tf.keras.models.load_model('CNN_best_wbc_model.h5', compile=False)

# Dummy focal loss function required to load the fine-tuned model
def categorical_focal_loss(gamma=2.0, alpha=0.25):
    def focal_loss(y_true, y_pred):
        return tf.keras.backend.sum(y_pred, axis=-1)
    return focal_loss

mobilenet_model = tf.keras.models.load_model(
    'MobileNetV2_best_wbc_model_finetuned.keras',
    custom_objects={'focal_loss': categorical_focal_loss()},
    compile=False
)

# --- 1. Compute FLOPs (Native TF Method) ---
def get_flops_native(model):
    concrete = tf.function(lambda inputs: model(inputs))
    concrete_func = concrete.get_concrete_function(
        [tf.TensorSpec([1, 120, 120, 3], tf.float32)])
    frozen_func, graph_def = convert_variables_to_constants_v2_as_graph(concrete_func)

    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        run_meta = tf.compat.v1.RunMetadata()
        opts = tf.compat.v1.profiler.ProfileOptionBuilder.float_operation()
        opts['output'] = 'none' # Suppress verbose output
        flops = tf.compat.v1.profiler.profile(graph=graph, run_meta=run_meta, cmd='op', options=opts)
        return flops.total_float_ops

print("\n--- FLOPs Comparison ---")
cnn_flops = get_flops_native(cnn_model)
mobile_flops = get_flops_native(mobilenet_model)

print(f"Custom CNN FLOPs: {cnn_flops / 1e6:.2f} MFLOPs")
print(f"MobileNetV2 FLOPs: {mobile_flops / 1e6:.2f} MFLOPs")

# --- 2. Compute Inference Time ---
print("\n--- Inference Time Comparison ---")
dummy_image = np.random.rand(1, 120, 120, 3).astype(np.float32)

def measure_inference_time(model, name):
    # Warm-up runs to initialize GPU/CPU graphs properly
    for _ in range(10):
        model.predict(dummy_image, verbose=0)

    # Actual benchmark over 100 runs
    start_time = time.time()
    for _ in range(100):
        model.predict(dummy_image, verbose=0)
    end_time = time.time()

    avg_time_ms = ((end_time - start_time) / 100) * 1000
    print(f"{name} Inference Time: {avg_time_ms:.2f} ms/image")

measure_inference_time(cnn_model, "Custom CNN")
measure_inference_time(mobilenet_model, "MobileNetV2")