# -*- coding: utf-8 -*-
"""MobileNetV2 model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfhotPVn4PilJYHgpbkTUBlbm3c82SlL

WBC Classification: MobileNetV2 with Transfer Learning

Project Overview

This notebook implements an advanced classification model using the MobileNetV2 architecture. This experiment is designed to contrast with the baseline CNN and test if more sophisticated, modern techniques can better address our three key research gaps.

The core hypothesis is that a pre-trained model will form a more robust and generalizable feature foundation.

Addressing the Research Gaps

This code is structured to directly investigate the following:

1. The Generalization Gap:

Problem: Models fail to generalize to new, out-of-domain data.

Hypothesis: A model pre-trained on a massive, diverse dataset (ImageNet) will learn more fundamental and robust visual features (edges, textures) than a model trained only on WBCs.

Our Approach:

Transfer Learning: We load a MobileNetV2 base pre-trained on ImageNet.

Two-Phase Fine-Tuning: We first train only the new classification head (Phase 1) and then unfreeze the top 50 layers of the base model to gently adapt the pre-trained features to our specific task (Phase 2).

2. The Lightweight XAI Gap:

Problem: Models must be efficient and interpretable.

Our Approach:

Lightweight: The MobileNetV2 architecture is inherently lightweight (approx. 2.2M parameters) and designed for high performance on mobile and edge devices.

XAI (Explainable AI): We implement Grad-CAM to produce heatmaps, allowing for a direct visual comparison of this model's "focus" against the baseline CNN's.

3. The Rare Class Gap:

Problem: The dataset is highly imbalanced.

Our Approach:

Instead of simple class weighting, we use a more advanced loss function: Categorical Focal Loss (gamma=2.0, alpha=0.25). This loss function dynamically down-weights the contribution of easy, well-classified examples (often the majority class), forcing the model to focus its efforts on learning the harder, more ambiguous examples (often the minority classes).
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tensorflow

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (Input, Conv2D, MaxPooling2D, Flatten,
                                     Dense, Dropout, BatchNormalization,
                                     Activation, GlobalAveragePooling2D)
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from google.colab import drive
from PIL import Image
import tensorflow.keras.backend as K
import gc

# --- Focal Loss Function ---
def categorical_focal_loss(gamma=2.0, alpha=0.25):
    """Implementation of Categorical Focal Loss."""
    def focal_loss(y_true, y_pred):
        epsilon = K.epsilon()
        y_pred = K.clip(y_pred, epsilon, 1. - epsilon)
        cross_entropy = -y_true * K.log(y_pred)
        loss = alpha * K.pow(1 - y_pred, gamma) * cross_entropy
        return K.sum(loss, axis=1)
    return focal_loss

# # --- 1. Mount Drive & Copy Data ---
print("Mounting Google Drive...")
drive.mount('/content/drive', force_remount=True)
ZIP_PATH = "/content/drive/My Drive/Datasets/Raabin-WBC_dataset.zip"
LOCAL_DEST = "/tmp/"
UNZIP_DIR = "/tmp/Raabin-WBC_dataset"
print("Copying dataset zip from Drive to local VM...")
!cp "{ZIP_PATH}" "{LOCAL_DEST}"
print("Unzipping dataset...")
!unzip -q /tmp/Raabin-WBC_dataset.zip -d /tmp/
BASE_DIR = UNZIP_DIR

# --- 2. Find and Delete Corrupted Files ---
train_dir_scan = os.path.join(BASE_DIR, 'Train')
bad_files = []
print(f"Scanning {train_dir_scan} for corrupted images...")
for root, dirs, files in os.walk(train_dir_scan):
    for file in files:
        file_path = os.path.join(root, file)
        try:
            img = Image.open(file_path); img.verify()
        except Exception as e:
            print(f"!!! BAD FILE FOUND: {file_path}"); bad_files.append(file_path)
if bad_files:
    print(f"\nFound {len(bad_files)} bad file(s). Deleting...");
    for f in bad_files: print(f"Deleting: {f}"); os.remove(f)
    print("Bad files deleted.")
else: print("\nScan complete. No bad files found.")

# --- 3. Define Paths & Hyperparameters ---
TRAIN_DIR = os.path.join(BASE_DIR, 'Train')
VALIDATION_DIR = os.path.join(BASE_DIR, 'TestA')
TEST_A_DIR = os.path.join(BASE_DIR, 'TestA')
TEST_B_DIR = os.path.join(BASE_DIR, 'Test-B')
IMAGE_SIZE = (120, 120)
BATCH_SIZE = 32
EPOCHS = 50
NUM_CLASSES = 5
LEARNING_RATE = 0.001

# --- 4. Data Preparation ---
train_datagen = ImageDataGenerator(
    preprocessing_function=mobilenet_preprocess,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest',
    brightness_range=[0.9, 1.1]
)
validation_test_datagen = ImageDataGenerator(preprocessing_function=mobilenet_preprocess)

train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR, target_size=IMAGE_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=True
)
validation_generator = validation_test_datagen.flow_from_directory(
    VALIDATION_DIR, target_size=IMAGE_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)
class_names = list(train_generator.class_indices.keys())
print(f"Class indices found: {train_generator.class_indices}")

test_generator_a = validation_test_datagen.flow_from_directory(
    TEST_A_DIR, target_size=IMAGE_SIZE, batch_size=1,
    class_mode='categorical', shuffle=False, classes=class_names
)
test_generator_b = validation_test_datagen.flow_from_directory(
    TEST_B_DIR, target_size=IMAGE_SIZE, batch_size=1,
    class_mode='categorical', shuffle=False, classes=class_names
)

# --- 5. Model Architecture (Function) ---
def build_transfer_model(input_shape, num_classes):
    base_model = MobileNetV2(
        input_shape=input_shape, include_top=False, weights='imagenet',
        name="my_mobilenet_base"
    )
    base_model.trainable = False
    inputs = Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)
    x = BatchNormalization()(x)
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.4)(x) # updated dropout
    outputs = Dense(num_classes, activation='softmax')(x)
    model = Model(inputs=inputs, outputs=outputs)
    return model

# --- Build Phase 1 Model ---
K.clear_session()
gc.collect()
model_phase1 = build_transfer_model(input_shape=IMAGE_SIZE + (3,), num_classes=NUM_CLASSES)
optimizer_phase1 = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)
model_phase1.compile(
    optimizer=optimizer_phase1,
    loss=categorical_focal_loss(gamma=2.0, alpha=0.25),
    metrics=['accuracy']
)
print("\n--- Phase 1 Model Summary (Base Frozen) ---")
model_phase1.summary()

# --- 6. Handling Class Imbalance ---
class_labels = np.unique(train_generator.classes)
class_weights = compute_class_weight(
    class_weight='balanced', classes=class_labels, y=train_generator.classes
)
class_weights_dict = dict(zip(class_labels, class_weights))
print("Calculated Class Weights:", class_weights_dict)

# --- 7. Phase 1 Training ---
print("\n--- Starting Phase 1 Training (Frozen Base) ---")
checkpoint_phase1 = ModelCheckpoint(
    'MobileNetV2_best_wbc_model_phase1.keras', monitor='val_accuracy', save_best_only=True,
    mode='max', verbose=1
)
# Define separate EarlyStopping for Phase 1
early_stopping_phase1 = EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True, verbose=1
)
lr_scheduler_phase1 = ReduceLROnPlateau(
    monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6, verbose=1
)
history_phase1 = model_phase1.fit(
    train_generator, validation_data=validation_generator, epochs=EPOCHS,
    callbacks=[checkpoint_phase1, early_stopping_phase1, lr_scheduler_phase1],
    #class_weight=class_weights_dict
)

# --- 8. Phase 1 Evaluation ---
# Define plotting and evaluation functions
def plot_training_history(history, title_prefix=""):
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Training Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.legend(loc='lower right'); plt.title(f'{title_prefix} Accuracy')
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Training Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.legend(loc='upper right'); plt.title(f'{title_prefix} Loss')
    plt.show()

def evaluate_model(model_path, test_generator, test_set_name):
    print(f"\n--- Evaluating {test_set_name} ---")
    if not os.path.exists(model_path):
        print(f"Warning: Model file '{model_path}' not found. Skipping evaluation.")
        return
    try:
        loaded_model = tf.keras.models.load_model(
            model_path,
            custom_objects={'focal_loss': categorical_focal_loss(gamma=2.0, alpha=0.25)}
        )
        test_loss, test_acc = loaded_model.evaluate(test_generator)
        print(f"{test_set_name} Accuracy: {test_acc:.4f}")
        print(f"{test_set_name} Loss: {test_loss:.4f}")
        test_generator.reset()
        Y_pred = loaded_model.predict(test_generator)
        y_pred = np.argmax(Y_pred, axis=1)
        y_true = test_generator.classes
        report_class_indices = sorted(np.unique(y_true))
        report_class_names = [class_names[i] for i in report_class_indices]
        print(f"\n--- {test_set_name} Classification Report ---")
        print(classification_report(y_true, y_pred, target_names=report_class_names, labels=report_class_indices))
        print(f"\n--- {test_set_name} Confusion Matrix ---")
        cm = confusion_matrix(y_true, y_pred, labels=report_class_indices)
        plt.figure(figsize=(8, 6)); sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=report_class_names, yticklabels=report_class_names)
        plt.title(f'{test_set_name} Confusion Matrix'); plt.ylabel('Actual Class'); plt.xlabel('Predicted Class'); plt.show()
    except Exception as e:
        print(f"Error during evaluation: {e}")

# Evaluate the best Phase 1 model
MODEL_PATH_PHASE1 = 'MobileNetV2_best_wbc_model_phase1.keras'
if history_phase1: plot_training_history(history_phase1, "Phase 1")
evaluate_model(MODEL_PATH_PHASE1, test_generator_a, "Phase 1 - Test Set A")
evaluate_model(MODEL_PATH_PHASE1, test_generator_b, "Phase 1 - Test Set B")

# --- 8.5 Phase 2: Fine-Tuning ---
print("\n--- Starting Phase 2: Fine-Tuning ---")
if not os.path.exists(MODEL_PATH_PHASE1):
    print("Phase 1 model not found. Skipping fine-tuning.")
else:
    # Load the best model from Phase 1
    model_phase2 = tf.keras.models.load_model(
        MODEL_PATH_PHASE1,
        custom_objects={'focal_loss': categorical_focal_loss(gamma=2.0, alpha=0.25)}
    )
    base_model = model_phase2.get_layer('my_mobilenet_base')
    base_model.trainable = True
    # Unfreeze top 50 layers
    print("Unfreezing top 50 layers of the base model...")
    for layer in base_model.layers[:-50]: layer.trainable = False

    # Re-compile with very low LR
    fine_tune_optimizer = tf.keras.optimizers.SGD(learning_rate=1e-5, momentum=0.9)
    model_phase2.compile(
        optimizer=fine_tune_optimizer,
        loss=categorical_focal_loss(gamma=2.0, alpha=0.25),
        metrics=['accuracy']
    )
    print("Model re-compiled for fine-tuning.")
    print("\n--- Phase 2 Model Summary (Base Unfrozen) ---")
    model_phase2.summary()

    # Determine starting epoch
    initial_epoch_for_finetune = 0
    if history_phase1: initial_epoch_for_finetune = len(history_phase1.history['loss'])
    else: print("Warning: Phase 1 history not found. Starting fine-tune from epoch 0.")

    FINE_TUNE_EPOCHS = 20
    TOTAL_EPOCHS_FINETUNE = initial_epoch_for_finetune + FINE_TUNE_EPOCHS

    # Callbacks for fine-tuning
    checkpoint_phase2 = ModelCheckpoint(
        'MobileNetV2_best_wbc_model_finetuned.keras', monitor='val_accuracy', save_best_only=True,
        mode='max', verbose=1
    )

    early_stopping_finetune = EarlyStopping(
        monitor='val_loss', patience=10, restore_best_weights=True, verbose=1
    )
    lr_scheduler_finetune = ReduceLROnPlateau(
        monitor='val_loss', factor=0.2, patience=3, min_lr=1e-7, verbose=1
    )

    print(f"\nContinuing training from epoch {initial_epoch_for_finetune}...")
    history_fine_tune = model_phase2.fit(
        train_generator, validation_data=validation_generator,
        epochs=TOTAL_EPOCHS_FINETUNE, initial_epoch=initial_epoch_for_finetune,
        callbacks=[checkpoint_phase2, early_stopping_finetune, lr_scheduler_finetune],
        #class_weight=class_weights_dict
    )

    # --- 8.6 Phase 2 Evaluation ---
    print("\n--- Fine-Tuning Complete. Evaluating fine-tuned model... ---")
    MODEL_PATH_FINETUNED = 'MobileNetV2_best_wbc_model_finetuned.keras'
    if history_fine_tune: plot_training_history(history_fine_tune, "Phase 2 Fine-Tune")
    evaluate_model(MODEL_PATH_FINETUNED, test_generator_a, "Fine-Tuned - Test Set A")
    evaluate_model(MODEL_PATH_FINETUNED, test_generator_b, "Fine-Tuned - Test Set B")

# --- 8.6 Phase 2 Evaluation ---
print("\n--- Fine-Tuning Complete. Evaluating fine-tuned model... ---")
MODEL_PATH_FINETUNED = 'MobileNetV2_best_wbc_model_finetuned.keras'
if history_fine_tune: plot_training_history(history_fine_tune, "Phase 2 Fine-Tune")
evaluate_model(MODEL_PATH_FINETUNED, test_generator_a, "Fine-Tuned - Test Set A")
evaluate_model(MODEL_PATH_FINETUNED, test_generator_b, "Fine-Tuned - Test Set B")

# --- Grad-CAM ---
import tensorflow as tf, numpy as np, matplotlib.pyplot as plt
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_preprocess
from tensorflow.keras import backend as K
import os

# --- small helpers
def get_img_array(img_path, size):
    img = tf.keras.preprocessing.image.load_img(img_path, target_size=size)
    arr = tf.keras.preprocessing.image.img_to_array(img)
    arr = np.expand_dims(arr, axis=0)
    return mobilenet_preprocess(arr)

def show_gradcam(img_path, heatmap, alpha=0.4):
    img = tf.keras.preprocessing.image.load_img(img_path)
    img = tf.keras.preprocessing.image.img_to_array(img)
    heatmap = np.uint8(255 * heatmap)
    jet = plt.cm.get_cmap("jet")
    jet_colors = jet(np.arange(256))[:, :3]
    jet_heatmap = jet_colors[heatmap]
    jet_heatmap = tf.keras.preprocessing.image.array_to_img(jet_heatmap)
    jet_heatmap = jet_heatmap.resize((img.shape[1], img.shape[0]))
    jet_heatmap = tf.keras.preprocessing.image.img_to_array(jet_heatmap)
    superimposed = jet_heatmap * alpha + img
    superimposed = tf.keras.preprocessing.image.array_to_img(superimposed)
    plt.imshow(superimposed); plt.axis('off'); plt.title('MobileNetV2 Heatmap'); plt.show()

#/content/MobileNetV2_best_wbc_model_finetuned.keras
MODEL_PATH = 'MobileNetV2_best_wbc_model_finetuned.keras'
SAMPLE_IMAGE_PATH = os.path.join(TEST_A_DIR, 'Neutrophil', '95-8-6-1_50_2.jpg')  # adjust if needed

assert os.path.exists(MODEL_PATH), f"Missing model: {MODEL_PATH}"
assert os.path.exists(SAMPLE_IMAGE_PATH), f"Missing image: {SAMPLE_IMAGE_PATH}"

# 1) Load the fine-tuned model
loaded_model = tf.keras.models.load_model(
    MODEL_PATH,
    custom_objects={'focal_loss': categorical_focal_loss(gamma=2.0, alpha=0.25)},
    compile=False
)

# 2) Grab the exact layer objects from your saved model
base = loaded_model.get_layer('my_mobilenet_base')
gap  = loaded_model.get_layer('global_average_pooling2d')
bn   = loaded_model.get_layer('batch_normalization')
fc1  = loaded_model.get_layer('dense')
do   = loaded_model.get_layer('dropout')
fc2  = loaded_model.get_layer('dense_1')

# 3) Load & preprocess image
img_array = get_img_array(SAMPLE_IMAGE_PATH, size=IMAGE_SIZE)
img_tensor = tf.convert_to_tensor(img_array)

# 4) Forward pass layer-by-layer
with tf.GradientTape() as tape:
    # base features
    feats = base(img_tensor, training=False)
    tape.watch(feats)

    # head
    x = gap(feats)
    x = bn(x, training=False)
    x = fc1(x)
    x = do(x, training=False)
    logits = fc2(x)
    preds = tf.nn.softmax(logits)

    # pick top predicted class
    pred_index = tf.argmax(preds[0])
    target = preds[:, pred_index]

# 5) Grad-CAM heatmap from feats -> target class
grads = tape.gradient(target, feats)
pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
feats = feats[0]
heatmap = feats @ pooled_grads[..., tf.newaxis]
heatmap = tf.squeeze(heatmap)
heatmap = tf.maximum(heatmap, 0) / (tf.reduce_max(heatmap) + K.epsilon())
heatmap = heatmap.numpy()

print(f"Pred idx={int(pred_index.numpy())}, prob={float(preds[0, pred_index]):.4f}, feats={feats.shape}")
show_gradcam(SAMPLE_IMAGE_PATH, heatmap)